version: '3'
services:
  postgres-metastore:
    image: postgres
    container_name: postgres-metastore
    environment:
      - POSTGRES_USER=hive
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=metastore_db
      - POSTGRES_INITDB_ARGS=--auth-host=md5
    volumes:
      - ./csv-files:/csv-files
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - my_network

  metastore:
    image: custom-hive-image
    container_name: hive-metastore
    environment:
      - SERVICE_NAME=metastore
      - HADOOP_CLASSPATH=/opt/jdbc/postgresql-42.5.1.jar
      - DB_DRIVER=postgres
      - SERVICE_OPTS=-Djavax.jdo.option.ConnectionDriverName=org.postgresql.Driver -Djavax.jdo.option.ConnectionURL=jdbc:postgresql://postgres-metastore:5432/metastore_db -Djavax.jdo.option.ConnectionUserName=hive -Djavax.jdo.option.ConnectionPassword=password  
    networks:
      - my_network
    volumes:
      - /Users/kumarrohit/Downloads/postgresql-42.5.1.jar:/opt/jdbc/postgresql-42.5.1.jar
    ports:
      - "9083:9083"
    depends_on:
      - postgres-metastore
    entrypoint:
      - "sh"
      - "-c"
      - "sleep 20 && /entrypoint.sh"
    command: ["standalone-metastore"]

  hive2:
    image: custom-hive-image
    container_name: hive2
    environment:
      - SERVICE_NAME=hiveserver2
      - SERVICE_OPTS=-Dhive.metastore.uris=thrift://hive-metastore:9083
      - IS_RESUME=true
    volumes:
      - ./postgresql-42.5.1.jar:/root/postgresql-42.5.1.jar
      - ./SparkScalaMaven-1.0-SNAPSHOT.jar:/root/SparkScalaMaven-1.0-SNAPSHOT.jar
      - ./automate_with_cron.sh:/root/automate_with_cron.sh
    networks:
      - my_network
    ports:
      - "10000:10000"
      - "10002:10002"
    command: ["sh", "-c", "service cron start && echo '* * * * * bash /root/automate_with_cron.sh' | crontab - "]

networks:
  my_network:
    driver: bridge

volumes:
  warehouse:

